### PR TITLE
fix moveTo function

### PR DESCRIPTION
**Pull request by micuat**
It seems your original implementation doesn't work for certain values and I couldn't understand how you are treating "error" values, so I rewrote some parts of the function.

### CODE REVIEW

**Comment by momostein** [comment]
First of all, thanks for contributing. Before i merge your changes, i would like to ask you some questions.

What 'certain values' do not work?

Also the algorithm i have implemented is [Bresenham's line algorithm](https://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm) but i refactored the math so it only uses integers. Integer math is faster than floating point math. I suggest you read this before changing the math.

PS: This was a school project i made 2 years ago and i kinda have abandoned this...

**Comment by micuat** [comment]
yes I understand the situation and sorry for the ambiguous comment - I'm in the middle of production so I will double check afterwards and get back to you

**Comment by micuat** [comment]
sorry this implementation is actually wrong; when Z axis is negative, other axes won't move (I think I was drunk when I was coding this)

**Comment by momostein** [comment]
Ok, no problem!

Thanks anyways. I will now close this pull request.

**Pull request closed without merging**
